public enum DungeonCode{
    YASUDAYA_RYOKAN,
    IZU_MITO_SEA_PARADISE,
    NUMAZU_DEEP_SEA_AQUARIUM,
    SHOUGETSU_CONFECTIONARY,
    NAGAHAMA_CASTLE_RUINS,
    NUMAZUGOYOTEI,
    UCHIURA_BAY_PIER,
    AWASHIMA_MARINE_PARK
}